### ISSUE TITLE
Package restore from the command line seems to fail.

### ISSUE THREAD

**Issue by ImaginateWayne** [jsakamoto/nupkg-selenium-webdriver-chromedriver#1]
When you Install-Package Selenium.WebDriver.ChromeDriver in Visual Studio the package is installed correctly though when you run a package restore from the command line the package doesn't run the init.ps1 file correctly and the chrome driver is not installed. 

I would recommend including the actual exe in the package itself, you shouldn't assume that the users have external internet access as NuGet.org can be proxied meaning the packages are only available to users internally thorugh a proxy server.

I hope that's helpful.
Wayne

**Comment by penguat** [comment]
This is proving to be a problem for me also - are you sure that the script will download on build, rather than on install? I'm using VS 2013, this problem makes it hard for me to share the package with my team, as well as causing build issues on our build server.

**Comment by jsakamoto** [comment]
It is only that I'm not sure about including chrome-driver - that is NOT my product - in my package is licensing violation or not.

You may can use follow NuGet package instead of my NuGet package.

https://www.nuget.org/packages/WebDriver.ChromeDriver.win32

That package include chrome-driver binary, I think it will resolve your problem, but I'm not sure about the package violate lisensing or not.

I hope this information helps you.
