### ISSUE TITLE
Chromedriver.exe version property

### ISSUE THREAD

**Issue by techworx** [jsakamoto/nupkg-selenium-webdriver-chromedriver#13]
I just started using chromedriver.exe v2.22.0.0 in C# .Net apps. Works beautifully.

Except for its output to console window (hidden in Release builds), I have not found a way to determine the version of chromedriver.exe at run time. The file 'chromedriver.exe' does not have version property (via Windows Explorer).

With Firefox WebDriver, I use the version of WebDriver.dll.

Packages.config provides the version during development, but once I start deploying to staging and live servers I don't see a way to keep track of the chromedriver.exe version.

Chrome WebDriver capabilities.Version provides the version of the Chrome _browser_. 
1. Is there a Chrome WebDriver method or property which provides the version of chromedriver.exe at runtime?
2. If not, is there a reason the file chromedriver.exe does not have a version property?

Thanks in advance,
Steve

**Comment by jsakamoto** [comment]
Sorry, I am **NOT** product owner of Chrome WebDriver.

I'm only packaging it for .NET Framework programmer.

> Q1. Is there a Chrome WebDriver method or property which provides the version of chromedriver.exe at runtime?

I don't know.  
Would you try to post the question something like a StackOverflow.com ?

> Q2. If not, is there a reason the file chromedriver.exe does not have a version property?

I don't know because I don't contribute developing chromedriver.exe.  
Would you try to contact chomedriver.exe community from here: https://sites.google.com/a/chromium.org/chromedriver/help

**Comment by hovankhon** [comment]
I want run hide chrome and console 
Help me
