### ISSUE TITLE
ChromeDriver binary is not copied to bin under .NET Core

### ISSUE THREAD

**Issue by disophisis** [jsakamoto/nupkg-selenium-webdriver-chromedriver#17]
We've moved an automation project to use the new .NET core project types and since then, ChromeDriver.exe is not copied to bin.  It appears NuGet uses a kind of centralized repository in %homepath%.nuget\packages.  Is there any plan (or is it even possible) to support the way this works under .NET Core?

**Comment by jsakamoto** [comment]
Could you let me show your all of project files on any internet servers, or send to me like a zip file?

You can send me any private messages via Twitter direct message ( My Twitter account is [@jsakamoto](https://twitter.com/jsakamoto) )

**Comment by JeremyTCD** [comment]
Hi thanks for publishing this package. I've encountered the same issue as @disophisis. Steps to reproduce: 

1. New project > Class Library (.Net Core)
2. Install-Package Selenium.WebDriver.ChromeDriver
3. Build

ChromeDriver.exe isn't copied to bin.

**Comment by jsakamoto** [comment]
I reproduced what you reported issue a few minutes ago. Thank you for tell me to operation steps.

But, this is the limitation of ".xdproj + project.json" style project for .NET Core. This style project does not consider about bundle any files exclude assembly referencing. This problem can not control by me. 

By the way, Microsoft **dropped ".xdproj + project.json" style project for .NET Core** in future version of Visual Studio and build environment. This is good news. We can get back ".csproj" style project for .NET Core.

I'm evaluation Visual Studio "2017" Release Candidate ( https://www.visualstudio.com/vs/visual-studio-2017-rc/ ).

In Visual Studio 2017 RC, 

1. New Project > Class Library (.NET Standard)
2. Install-Package Selenium.WebDriver.ChromeDriver
3. Build

Then, ChromeDriver.exe is exists bin folder. 😄  
There is ".csproj" file instead of ".xdproj + project.json".

Conclusion
-------------
I can not resolve this issue in VS2015.  
But future version of Visual Studio resolve this issue.

**Comment by JeremyTCD** [comment]
Hey thanks for the quick response! You are right about Microsoft reverting to MSBuild/.csproj for .Net Core. I guess this issue can be closed 👍.

**Comment by disophisis** [comment]
I just got the notifications on these responses and realized I totally forgot to come back and follow up here.  I apologize for leaving this open without providing feedback!

I agree with @JeremyTCD this can be closed.  We will probably move to VS 2017 whenever it makes sense to do so and this problem should resolve itself. 👍
