### ISSUE TITLE
The usage of [System.Text.RegularExpressions.Regex]::IsMatch breaks Xamarin compatibility

### ISSUE THREAD

**Issue by lipebento** [jsakamoto/nupkg-selenium-webdriver-chromedriver#20]
Projects with ChromeDriver packages no longer build on Xamarin. The IDE should be handling dependencies in the same way as Visual Studio, however, it cannot find the implementation for the IsMatch function of Selenium.WebDriver.ChromeDriver.targets.

Adding an explicit dependency on nuspec should fix the issue.
https://www.nuget.org/packages/System.Text.RegularExpressions/

Error seen on Xamarin 6.2 on macOS Sierra:
```Error: Field 'System.Text.RegularExpressions.Regex.IsMatch' not found.```

**Comment by jsakamoto** [comment]
@lipebento I'm sorry for the late reply.

This issue has two point things.

1st, the error "Field 'System.Text.RegularExpressions.Regex.IsMatch' not found" was occurred in build system, so adding an explicit dependency on nuspec will not fix the issue.

If I add an explicit dependency on nuspec, but it will effect only adding reference of the assembly which contains RegularExpression class into the project that install this NuGet package, and it will not resolve this issue.

2nd, this NuGet package contains chrome driver of **Win32 binary only!**

If we resolve the 1st point "Field 'System.Text.RegularExpressions.Regex.IsMatch' not found" error, but we can not run the project on macOS, and Linux OS! (because this NuGet package doesn't provide the chrome driver executable files for those OS.)

I'm interested in this issue, so I'll keep trying to resolve this issue.  
For example, I'll look into how to include multiple binaries for each OS platforms.

But it will need more days.

**Comment by lipebento** [comment]
Thanks @jsakamoto. I'll update this issue in case I find any more details on how to resolve this. You're right that my proposed solution won't work. I'm starting to believe this is an issue with Xamarin not handling the target files properly.

**Comment by jsakamoto** [comment]
@lipebento I did it!

https://twitter.com/jsakamoto/status/837506979136319488
![image](https://cloud.githubusercontent.com/assets/95908/23537347/ba7a1474-000e-11e7-93d0-aea3ee0ccf1e.png)

Could you try to v.2.27.0.7 Beta?
https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/2.27.0.7-beta

**Comment by nkurt** [comment]
Have the same issue on Linux after updating from v.2.25.0.0 to v.2.28.0. Tried v.2.27.0.7 Beta but it didn't helped.

**Comment by jsakamoto** [comment]
@nkurt Excuse me, I had not say "Linux supported"...

This package dose **NOT** include chrome driver for Linux binary in the fist place.

But I'm interest in Linux support, so could you tell more details of your development environment? (Which distribution do you use? What IDE or editor do you use? What is the processor architecture of the Linux OS that you are using?)

**Comment by nkurt** [comment]
@jsakamoto I have a project that I build on both Windows and Linux. In fact I don't need a Linux binary for chromedriver. I just need to build my project in docker using mono. Unfortunately my project fails to build after updating to  v.2.28.0. I receive the following error:
`Field 'System.Text.RegularExpressions.Regex.IsMatch' not found `

**Comment by jsakamoto** [comment]
@nkurt Thank you for your reply.  
I feel the problem is clearly due to your information.

I hope please try to v.2.28.0.1-Beta:  
https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/2.28.0.1-beta

This version was removed using `System.Text.RegularExpressions.Regex.IsMatch` since 2.27.0.2-Beta by commit a0b5846c053f6fff380b970a068eea726f14a2a0.

But you said, 

> Tried v.2.27.0.7 Beta but it didn't helped.

...what happen?

v.2.27.0.7 Beta dose not contain the build script code `System.Text.RegularExpressions.Regex.IsMatch`, but you ran into the same error??

If you have enough time, I expect you will figure out to more details.

And, I also will try to reproduce the error you encounter. I'm making the environment such as VirtualBox virtual machine, install Ubuntu Desktop, and so on.

**Comment by lipebento** [comment]
@jsakamoto thank you for the support. I will test it soon and let you know.

**Comment by jsakamoto** [comment]
@lipebento Please try v.2.28.0.2-beta if you can. 

I tried v.2.28.0.1-beta, but I detected it has problem 😭

But at last, I was successful to build on Mono in Ubuntu Desktop 16 LTS due to create new package v.2.28.0.2-beta. 

![image](https://cloud.githubusercontent.com/assets/95908/24152748/dd03922e-0e8f-11e7-838e-95fa1d585ba7.png)

I know that you don't need running WebDriver on Linux, you only need building project successful, anyway, I hope the v.2.28.0.2-beta helps you.

**Comment by jsakamoto** [comment]
P.S. The package v.2.28.0.2-beta support only 64 bit kernel Linux.

**Comment by nkurt** [comment]
@jsakamoto sorry for late response. Thank you! You are the best!
