### ISSUE TITLE
Cannot Start Driver Service -- Running on Windows Server 2012 R2

### ISSUE THREAD

**Issue by jparks2** [jsakamoto/nupkg-selenium-webdriver-chromedriver#29]
Hi,

I have a program that uses the headless option of the Chrome Driver in executing its function, but the program throws an exception "Cannot start the driver service" when the program runs on a Windows Server 2012 R2 machine. 

The program runs fine on my local laptop. Is the Chrome Driver compatible with Windows Server 2012 R2?

Thanks,
jparks2

**Comment by xzessmedia** [comment]
same here… this is really important for me

**Comment by jparks2** [comment]
Any update on this? I appreciate you looking into this jsakamoto. 

Thanks,
jparks2

**Comment by jsakamoto** [comment]
I tried to run a sample program to reproduce your problem, but was run successful.

![image](https://user-images.githubusercontent.com/95908/45420966-8c64db80-b6c6-11e8-80f5-7e7d323a0763.png)

The environment of this sample program is:

- Hyper-V Virtual Machine - Intel Core i7 7660U 2vCPU / 2GB RAM 
- Windows Server 2012 R2 Standard x64 EN GUI Install ver.6.4.9600, All updates are applied.
- Google Chrome Version 69.0.3497.92 (Official Build) (64-bit)
- Visual Studio Community 2017 v.15.8.4
- .NET Framework 4.5
- Selenium.WebDriver ver.3.14
- Selenium.WebDriver.ChromeDriver ver.2.41

The source code is here:

- [ConsoleApp1.zip](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/files/2374805/ConsoleApp1.zip)

However, I know, your problem was occurred on **headless** mode.

Please let me know about more and more detail of your environment, and, please provide minimal sample source code that can reproduce the problem at least on your environment.

**Comment by jsakamoto** [comment]
Thanks @jparks2. Hey @xzessmedia, is your problem is same reason?

To: @jparks2 , I guess, your bug depends on only environment of the run time, not depends on OS.

For example, If the current directory is "C:\foo",  `Directory.GetCurrentDirectory()` return `"C:\foo"`.
However, when the current directory is "C:\",  `Directory.GetCurrentDirectory()` return `"C:\"`.
Please watch the end of character is "\", or not.

Therefore, when the current directory is "C:\",  you will get invalid path like "C:**\\**output.log".

In this case, you must use `Path.Combine()` instead of concatenating strings directly.

I can think more and more another reasons that doesn't depend on OS types, such as the program doesn't have enough permission to writing a log file into current directory, etc, etc, ...

I hope this my post helpful for you.

**Comment by jsakamoto** [comment]
Since there is no responses, I'll close this issue.

If anybody still have same problem, feel free to reopen this issue.
