### ISSUE TITLE
"chromedriver.exe file does not exist" error after installing

### ISSUE THREAD

**Issue by olaeld** [jsakamoto/nupkg-selenium-webdriver-chromedriver#55]
When I start a new project, this line causes an error:
using (IWebDriver driver = new ChromeDriver())

The error message is:
OpenQA.Selenium.DriverServiceNotFoundException : The chromedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html.

I was able to overcome the problem by changing the line into this:
using (IWebDriver driver = new ChromeDriver(Environment.CurrentDirectory))

It would be nice if it just worked "out of the box", though...

**Comment by jsakamoto** [comment]
You can do same thing by using `AppDomain.CurrentDomain.BaseDirectory` instead of `Environment.CurrentDirectory` like  bellow.

```csharp
using (IWebDriver driver = new ChromeDriver(AppDomain.CurrentDomain.BaseDirectory))
```
See also: https://translate.google.com/translate?sl=ja&tl=en&u=https%3A%2F%2Fdevadjust.exblog.jp%2F27257580%2F (This is machine translation. Original contents is Japanese.)

> It would be nice if it just worked "out of the box", though...

I **strongly agree**, too!

However, this is by design of the developer of Selenium .NET porting.  
I want to change this behavior, but the developer rejected this proposal... 😢
