### ISSUE TITLE
chromedriver.exe 101.0.4951.54 

### ISSUE THREAD

**Issue by AtakanTanrisever** [jsakamoto/nupkg-selenium-webdriver-chromedriver#89]
When will the new update come?

**[IMPORTANT] This repository is just for packaging, not for chromedriver itself**

Therefore, do not post an issue about the problems of the behavior of chromedriver.

Instead, you can ask somebody in "stack overflow" site: https://stackoverflow.com/questions/tagged/selenium

**Comment by jsakamoto** [comment]
> When will the new update come?

The new update will come when it appear on the site https://chromedriver.storage.googleapis.com/index.html.

In most case, I've provided each new release in 24 hours since the new version appeared on that site.

I can not see the ver.101.0.4951.54 on that site so far.

![image](https://user-images.githubusercontent.com/95908/167731890-30a4abf4-d283-438b-9b28-84f5eb069543.png)

**Comment by jsakamoto** [comment]
Is it possible that you might misunderstand the version of chrome drivers?
The version of chrome drivers is not always matched as chrome web browser's one.

**Comment by AtakanTanrisever** [comment]
![image](https://user-images.githubusercontent.com/25545296/169834118-a1fabf48-6738-4b15-8a50-4711be4840e8.png)

The error I get is as above. waiting for your help.

**Comment by AtakanTanrisever** [comment]
![image](https://user-images.githubusercontent.com/25545296/170256474-a9ace172-b4d0-4434-9d02-c31c31c5886e.png)

You can see the code in the image above. It gives the error I sent in the second line. I am using .net framework. Other images are as attached. My operating system is windows 10

![image](https://user-images.githubusercontent.com/25545296/170257035-2e9677d1-e343-4618-b9f4-02dfd0d39f1d.png)
