### ISSUE TITLE
`chromedriver.exe` file not found in `packages` directory

### ISSUE THREAD

**Issue by astrohart** [jsakamoto/nupkg-selenium-webdriver-chromedriver#97]
@jsakamoto 

![image](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/assets/8261875/c72f65ed-7fea-44e2-9645-7eea9984e5cf)
**Figure 1.** No `chromedriver.exe` present in the `packages` folder.  Can't build.

Getting a "file not found" error in the `packages` directory of my .NET Framework 4.8.1 project that has the `Selenium.WebDriver.ChromeDriver` NuGet package version `120.0.6099.7100` installed into it.

I am getting a build error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\Brian Hart\source\repos\****\****.VS2019\packages\Selenium.WebDriver.ChromeDriver.120.0.6099.7100\build\..\driver\win32\chromedriver.exe" because it was not found.	***.Processes			

```

Perhaps was its inclusion in the NuGet download for `win32` forgotten?  Thank you.

**Comment by jsakamoto** [comment]
Hi @astrohart,

I think that problem depends on particular your environment because I investigated it with the following instructions.

----

I downloaded the "Selenium.WebDriver.ChromeDriver" NuGet package from the nuget.org,

![image](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/assets/95908/1cbe9268-7f34-4d67-83a3-3858ddff6cad)

and I opened it by the [NuGet Package Explorer](https://apps.microsoft.com/detail/9WZDNCRDMDM3?hl=en-US&gl=US), then I could see there was a "chromedriver.exe" in the appropriate folder.

![image](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/assets/95908/4cc78882-3491-4041-aedc-ee0d57d76075)

----

I also cleared the NuGet package cache, created a new .NET Framework 4.8.1 console application, and added the "Selenium.WebDriver.ChromeDrive" NuGet package, and run it. It ran correctly.

- [📦ConsoleApp1.zip](https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/files/13694367/ConsoleApp1.zip)

----

According to the screenshot you attached, a license file remained in the folder, so I guess some kind of security software deleted only the executable binary file, "chromedriver.exe", from that folder because the security software judged it as malware.

**Comment by astrohart** [comment]
This issue can be closed. It’s my bad. I had accidentally erased the file from within the packages folder by means of running a script that wasn’t written correctly. I’ve confirmed that this was an error on my side, and has nothing to do with the operation of the package.Thanks for the support. Regards, Brian HartOn Dec 16, 2023, at 18:23, jsakamoto ***@***.***> wrote:﻿
Hi @astrohart,
I think that problem depends on particular your environment because I investigated it with the following instructions.

I downloaded the "Selenium.WebDriver.ChromeDriver" NuGet package from the nuget.org,
image.png (view on web)
and I opened it by the NuGet Package Explorer, then I could see there was a "chromedriver.exe" in the appropriate folder.
image.png (view on web)

I also cleared the NuGet package cache, created a new .NET Framework 4.8.1 console application, and added the "Selenium.WebDriver.ChromeDrive" NuGet package, and run it. It ran correctly.

📦ConsoleApp1.zip


According to the screenshot you attached, a license file remained in the folder, so I guess some kind of security software deleted only the executable binary file, "chromedriver.exe", from that folder because the security software judged it as malware.

**Comment by jsakamoto** [comment]
@astrohart 
No problem! I've experienced many times that we helped by reporting from users even though those reports sometimes looked like they were not the matter of the ChromeDriver NuGet package side, apparently.
I always welcome any reports from users.
Thank you for your contributions! ❤️
